baseURL = 'https://creampnx-x.github.io/blog/'
languageCode = 'en-us'
title = 'Blog'
theme = 'PaperMod'
enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'


enableRobotsTXT=true
buildDrafts=false
buildFuture=false
buildExpired=false

[params]
  [params.homeInfoParams]
    Title = "é©¬è‡´è‰¯çš„æ–‡ç« "
    Content = " ğŸ‘‹ åé¢ï¼Œè¿™é‡Œå°†ä¼šæœ‰ä¸€äº›æ–‡ç«  "

  [params.assets]
    disableHLJS = true
    favicon = "/blog/favicon.ico?v=1.0"

  [[params.socialIcons]]
      name = "github"
      title = "View Source on Github"
      url = "https://github.com/creampnx-x/blog" 